const pl = {
  'Back to project':'Wróć do projektu','CASE STUDY':'CASE STUDY','Overview':'Przegląd','Problem':'Problem','Strategy':'Strategia','User flows':'Przepływy użytkownika','Key decisions':'Kluczowe decyzje','Design system':'System projektowy','Reflection':'Wnioski',
  'ELLIS BANK · UX CASE STUDY':'ELLIS BANK · UX CASE STUDY','How do you make':'Jak sprawić, by','money feel':'finanse dawały','quieter?':'więcej spokoju?','A premium mobile banking concept that treats clarity, trust and emotional comfort as core product features.':'Koncepcja premium bankowości mobilnej, w której jasność, zaufanie i komfort emocjonalny są kluczowymi cechami produktu.',
  'MY ROLE':'MOJA ROLA','Product Designer':'Projektant produktu','SCOPE':'ZAKRES','End-to-end concept':'Koncepcja end-to-end','PLATFORM':'PLATFORMA','Trust, made visible':'Zaufanie, które widać','Security without friction':'Bezpieczeństwo bez tarcia',
  '“Premium” should not mean more features on screen. It should mean fewer moments of doubt.':'„Premium” nie powinno oznaczać większej liczby funkcji na ekranie. Powinno oznaczać mniej momentów niepewności.','steps to transfer':'kroki do przelewu','tap to freeze a card':'dotknięcie, by zamrozić kartę','level for daily tasks':'poziom dla codziennych zadań','minimum touch target':'minimalny obszar dotyku',
  'THE PROBLEM':'PROBLEM','More information. Less confidence.':'Więcej informacji. Mniej pewności.','Banking dashboards often compete for attention exactly when users need calm, speed and certainty.':'Pulpity bankowe często walczą o uwagę właśnie wtedy, gdy użytkownicy potrzebują spokoju, szybkości i pewności.','The paradox':'Paradoks','Modern banks add features to create value, but dense dashboards can bury the very actions people use most. Premium clients do not need fewer capabilities. They need better timing and hierarchy.':'Nowoczesne banki dodają funkcje, lecz gęste pulpity ukrywają najczęstsze działania. Klienci premium nie potrzebują mniej możliwości — potrzebują lepszego czasu i hierarchii.','Overwhelming dashboards':'Przytłaczające pulpity','Hidden security controls':'Ukryte ustawienia bezpieczeństwa','Hard-to-scan activity':'Trudna do przejrzenia aktywność','Uncertain transfer states':'Niejasne stany przelewu','TYPICAL DASHBOARD':'TYPOWY PULPIT','ELLIS HOME':'PULPIT ELLIS','3 clear actions':'3 jasne działania','A note on evidence':'Nota o podstawach','This is a concept project. The problem framing is based on heuristic analysis and category patterns—not claimed user research. The next research step is defined at the end of this case study.':'To projekt koncepcyjny. Problem zdefiniowano na podstawie analizy heurystycznej i wzorców kategorii, a nie deklarowanych badań użytkowników. Kolejny krok badawczy opisano na końcu case study.',
  'PRODUCT STRATEGY':'STRATEGIA PRODUKTU','Calm is a system, not a style.':'Spokój to system, nie styl.','The interface is guided by five principles that turn the emotional goal into repeatable product decisions.':'Interfejs opiera się na pięciu zasadach, które zmieniają cel emocjonalny w powtarzalne decyzje produktowe.','Clarity before decoration':'Jasność przed dekoracją','Every screen states its purpose immediately.':'Każdy ekran od razu komunikuje swój cel.','Important information first':'Najpierw ważne informacje','Balance before detail. Actions before settings.':'Saldo przed szczegółami. Działania przed ustawieniami.','Progressive disclosure':'Stopniowe ujawnianie','Complexity waits until it is useful.':'Złożoność czeka, aż będzie potrzebna.','Predictable patterns':'Przewidywalne wzorce','Position and meaning stay consistent.':'Pozycja i znaczenie pozostają spójne.','Calm banking':'Spokojna bankowość','Nothing flashes or competes for attention.':'Nic nie miga ani nie walczy o uwagę.','PRIMARY AUDIENCE':'GŁÓWNA GRUPA','Designed for financially active lives.':'Zaprojektowane dla aktywnego życia finansowego.','Professionals 25–50':'Specjaliści 25–50','Frequent travelers':'Często podróżujący','Freelancers':'Freelancerzy','Business owners':'Właściciele firm','Multi-account users':'Użytkownicy wielu kont',
  'FLOWS & ARCHITECTURE':'PRZEPŁYWY I ARCHITEKTURA','Everyday tasks stay shallow.':'Codzienne zadania pozostają płytkie.','The navigation never exceeds one level of depth for common actions. Context carries users forward; menus do not make them hunt.':'Nawigacja dla typowych działań nie przekracza jednego poziomu. Kontekst prowadzi użytkownika dalej, bez szukania w menu.','Send money':'Wyślij pieniądze','High-confidence path':'Ścieżka wysokiej pewności','Home':'Start','Recipient':'Odbiorca','Amount':'Kwota','Review':'Podsumowanie','Success':'Sukces','Receipt':'Potwierdzenie','Customize card':'Personalizuj kartę','Emotional utility':'Wartość emocjonalna','Card':'Karta','Customize':'Personalizacja','Color':'Kolor','Save':'Zapisz','Updated':'Zaktualizowano','5 destinations':'5 sekcji','Cards':'Karty','Payments':'Płatności','Analytics':'Analityka','Profile':'Profil',
  'KEY UX DECISIONS':'KLUCZOWE DECYZJE UX','Confidence is designed into the sequence.':'Pewność została wpisana w sekwencję.','DECISION 01 · HOME':'DECYZJA 01 · START','A dashboard with an opinion.':'Pulpit z wyraźnym priorytetem.','The home screen does not try to summarize the entire bank. It answers three questions first: “How much do I have?”, “What can I do?” and “What just happened?”':'Ekran główny nie próbuje podsumować całego banku. Najpierw odpowiada na trzy pytania: „Ile mam?”, „Co mogę zrobić?” i „Co się właśnie wydarzyło?”.','Hierarchy':'Hierarchia','DECISION 02 · TRANSFER':'DECYZJA 02 · PRZELEW','Review before commitment.':'Sprawdź przed zatwierdzeniem.','Recipient, amount, source account, fee and speed remain visible together at the moment of confirmation. The user should never need memory to verify a transfer.':'Odbiorca, kwota, konto źródłowe, opłata i czas pozostają widoczne w chwili potwierdzenia. Użytkownik nie musi polegać na pamięci.','Error prevention':'Zapobieganie błędom','One review screen, one deliberate action':'Jedno podsumowanie, jedno świadome działanie','DECISION 03 · ANALYTICS':'DECYZJA 03 · ANALITYKA','Answers, not reports.':'Odpowiedzi, nie raporty.','Analytics is organized around plain questions: where, how much and compared to when. Charts support the answer instead of becoming the task.':'Analityka odpowiada na proste pytania: gdzie, ile i w porównaniu z kiedy. Wykres wspiera odpowiedź, zamiast stawać się zadaniem.','Progressive detail':'Stopniowe szczegóły','Summary first, category depth on demand':'Najpierw podsumowanie, szczegóły na żądanie',
  'DESIGN SYSTEM':'SYSTEM PROJEKTOWY','Soft visually. Rigorous underneath.':'Miękki wizualnie. Rygorystyczny w podstawach.','The visual language pairs private-banking warmth with a predictable 8-point system and accessible interaction rules.':'Język wizualny łączy ciepło private banking z przewidywalnym systemem 8-punktowym i dostępnymi zasadami interakcji.','TYPOGRAPHY':'TYPOGRAFIA','Elegant when it speaks.':'Elegancki, gdy mówi.','Quiet when it explains.':'Spokojny, gdy wyjaśnia.','COLOR':'KOLOR','CORE TOKENS':'GŁÓWNE TOKENY','pt grid':'siatka pt','px radius':'promień px','px touch':'dotyk px','ms motion':'ruch ms','Contrast':'Kontrast','Text remains legible across soft surfaces.':'Tekst pozostaje czytelny na delikatnych powierzchniach.','Non-color cues':'Sygnały poza kolorem','State always includes shape, icon or label.':'Stan zawsze obejmuje kształt, ikonę lub etykietę.','Motion restraint':'Powściągliwy ruch','Clear labels':'Jasne etykiety','Security actions never rely on icons alone.':'Działania bezpieczeństwa nigdy nie opierają się wyłącznie na ikonach.',
  'REFLECTION':'WNIOSKI','What this concept proves—and what it does not.':'Co ta koncepcja udowadnia — i czego nie.','THE PRODUCT BET':'HIPOTEZA PRODUKTOWA','Emotional comfort can be functional.':'Komfort emocjonalny może być funkcjonalny.','Calm hierarchy, explicit confirmation and restrained motion do more than create a premium aesthetic. They can reduce hesitation and help users understand consequences before acting.':'Spokojna hierarchia, jasne potwierdzenia i oszczędny ruch robią więcej niż tworzenie estetyki premium. Mogą zmniejszać wahanie i pomagać zrozumieć konsekwencje przed działaniem.','WHAT I’D VALIDATE NEXT':'CO SPRAWDZIŁABYM DALEJ','Can users find card security controls without prompting?':'Czy użytkownicy znajdą zabezpieczenia karty bez podpowiedzi?','Do transfer review details reduce backtracking?':'Czy szczegóły podsumowania przelewu ograniczają cofanie?','Which home-screen modules earn their place?':'Które moduły ekranu głównego zasługują na miejsce?','Does personalization increase attachment without distraction?':'Czy personalizacja zwiększa przywiązanie bez rozpraszania?','01 · DISCOVER':'01 · ODKRYWANIE','6 moderated interviews':'6 moderowanych wywiadów','Map anxiety, routines and language around money movement.':'Poznanie obaw, rutyn i języka związanego z przepływem pieniędzy.','02 · TEST':'02 · TEST','Task-based prototype':'Prototyp zadaniowy','Transfer, freeze a card and understand monthly spend.':'Przelew, zamrożenie karty i zrozumienie miesięcznych wydatków.','03 · MEASURE':'03 · POMIAR','Confidence + completion':'Pewność + ukończenie','Track success, errors, time, backtracking and perceived certainty.':'Pomiar sukcesu, błędów, czasu, cofania i odczuwanej pewności.','Thank you for':'Dziękuję za','following the thinking.':'prześledzenie procesu.','Back to visual project':'Wróć do projektu','Concept project':'Projekt koncepcyjny'
};

const uk = {
  'Back to project':'Назад до проєкту','CASE STUDY':'КЕЙС UX','Overview':'Огляд','Problem':'Проблема','Strategy':'Стратегія','User flows':'Сценарії','Key decisions':'Ключові рішення','Design system':'Дизайн-система','Reflection':'Висновки',
  'ELLIS BANK · UX CASE STUDY':'ELLIS BANK · UX КЕЙС','How do you make':'Як зробити','money feel':'фінанси','quieter?':'спокійнішими?','A premium mobile banking concept that treats clarity, trust and emotional comfort as core product features.':'Концепція преміального мобільного банкінгу, де ясність, довіра та емоційний комфорт є ключовими властивостями продукту.',
  'MY ROLE':'МОЯ РОЛЬ','Product Designer':'Продуктовий дизайнер','SCOPE':'ОБСЯГ','End-to-end concept':'Наскрізна концепція','PLATFORM':'ПЛАТФОРМА','Trust, made visible':'Довіра, яку видно','Security without friction':'Безпека без зайвих кроків',
  '“Premium” should not mean more features on screen. It should mean fewer moments of doubt.':'«Преміум» — це не більше функцій на екрані. Це менше моментів сумніву.','steps to transfer':'кроки до переказу','tap to freeze a card':'дотик, щоб заморозити картку','level for daily tasks':'рівень для щоденних дій','minimum touch target':'мінімальна зона дотику',
  'THE PROBLEM':'ПРОБЛЕМА','More information. Less confidence.':'Більше інформації. Менше впевненості.','Banking dashboards often compete for attention exactly when users need calm, speed and certainty.':'Банківські панелі часто змагаються за увагу саме тоді, коли користувачам потрібні спокій, швидкість і впевненість.','The paradox':'Парадокс','Modern banks add features to create value, but dense dashboards can bury the very actions people use most. Premium clients do not need fewer capabilities. They need better timing and hierarchy.':'Сучасні банки додають функції, але перевантажені панелі приховують найчастіші дії. Преміальним клієнтам потрібні не менші можливості, а краща ієрархія.','Overwhelming dashboards':'Перевантажені панелі','Hidden security controls':'Приховані налаштування безпеки','Hard-to-scan activity':'Складна для перегляду активність','Uncertain transfer states':'Незрозумілі стани переказу','TYPICAL DASHBOARD':'ТИПОВА ПАНЕЛЬ','ELLIS HOME':'ГОЛОВНА ELLIS','3 clear actions':'3 зрозумілі дії','A note on evidence':'Примітка про підґрунтя','This is a concept project. The problem framing is based on heuristic analysis and category patterns—not claimed user research. The next research step is defined at the end of this case study.':'Це концептуальний проєкт. Формулювання проблеми базується на евристичному аналізі та патернах категорії, а не на заявленому дослідженні користувачів. Наступний крок описано наприкінці кейсу.',
  'PRODUCT STRATEGY':'ПРОДУКТОВА СТРАТЕГІЯ','Calm is a system, not a style.':'Спокій — це система, а не стиль.','The interface is guided by five principles that turn the emotional goal into repeatable product decisions.':'Інтерфейс спирається на п’ять принципів, які перетворюють емоційну мету на повторювані продуктові рішення.','Clarity before decoration':'Ясність перед декором','Every screen states its purpose immediately.':'Кожен екран одразу пояснює своє призначення.','Important information first':'Важливе — спочатку','Balance before detail. Actions before settings.':'Баланс перед деталями. Дії перед налаштуваннями.','Progressive disclosure':'Поступове розкриття','Complexity waits until it is useful.':'Складність з’являється лише тоді, коли потрібна.','Predictable patterns':'Передбачувані патерни','Position and meaning stay consistent.':'Позиція та значення залишаються послідовними.','Calm banking':'Спокійний банкінг','Nothing flashes or competes for attention.':'Ніщо не блимає й не змагається за увагу.','PRIMARY AUDIENCE':'ОСНОВНА АУДИТОРІЯ','Designed for financially active lives.':'Створено для фінансово активного життя.','Professionals 25–50':'Професіонали 25–50','Frequent travelers':'Активні мандрівники','Freelancers':'Фрилансери','Business owners':'Власники бізнесу','Multi-account users':'Користувачі кількох рахунків',
  'FLOWS & ARCHITECTURE':'СЦЕНАРІЇ ТА АРХІТЕКТУРА','Everyday tasks stay shallow.':'Щоденні завдання залишаються простими.','The navigation never exceeds one level of depth for common actions. Context carries users forward; menus do not make them hunt.':'Навігація для типових дій не перевищує одного рівня. Контекст веде вперед без пошуку в меню.','Send money':'Надіслати гроші','High-confidence path':'Сценарій високої впевненості','Home':'Головна','Recipient':'Отримувач','Amount':'Сума','Review':'Перевірка','Success':'Успіх','Receipt':'Квитанція','Customize card':'Налаштувати картку','Emotional utility':'Емоційна цінність','Card':'Картка','Customize':'Налаштування','Color':'Колір','Save':'Зберегти','Updated':'Оновлено','5 destinations':'5 розділів','Cards':'Картки','Payments':'Платежі','Analytics':'Аналітика','Profile':'Профіль',
  'KEY UX DECISIONS':'КЛЮЧОВІ UX-РІШЕННЯ','Confidence is designed into the sequence.':'Впевненість закладена в послідовність.','DECISION 01 · HOME':'РІШЕННЯ 01 · ГОЛОВНА','A dashboard with an opinion.':'Панель із чітким пріоритетом.','The home screen does not try to summarize the entire bank. It answers three questions first: “How much do I have?”, “What can I do?” and “What just happened?”':'Головний екран не намагається підсумувати весь банк. Спочатку він відповідає на три питання: «Скільки в мене є?», «Що я можу зробити?» і «Що щойно сталося?».','Hierarchy':'Ієрархія','DECISION 02 · TRANSFER':'РІШЕННЯ 02 · ПЕРЕКАЗ','Review before commitment.':'Перевірка перед підтвердженням.','Recipient, amount, source account, fee and speed remain visible together at the moment of confirmation. The user should never need memory to verify a transfer.':'Отримувач, сума, рахунок, комісія та швидкість одночасно видимі під час підтвердження. Користувачеві не потрібно покладатися на пам’ять.','Error prevention':'Запобігання помилкам','One review screen, one deliberate action':'Один екран перевірки, одна свідома дія','DECISION 03 · ANALYTICS':'РІШЕННЯ 03 · АНАЛІТИКА','Answers, not reports.':'Відповіді, а не звіти.','Analytics is organized around plain questions: where, how much and compared to when. Charts support the answer instead of becoming the task.':'Аналітика побудована навколо простих запитань: де, скільки і порівняно з яким періодом. Графіки підтримують відповідь, а не стають завданням.','Progressive detail':'Поступова деталізація','Summary first, category depth on demand':'Спочатку підсумок, деталі — за потреби',
  'DESIGN SYSTEM':'ДИЗАЙН-СИСТЕМА','Soft visually. Rigorous underneath.':'М’яка візуально. Строга в основі.','The visual language pairs private-banking warmth with a predictable 8-point system and accessible interaction rules.':'Візуальна мова поєднує тепло private banking із передбачуваною 8-пунктовою системою та доступними правилами взаємодії.','TYPOGRAPHY':'ТИПОГРАФІКА','Elegant when it speaks.':'Елегантна, коли говорить.','Quiet when it explains.':'Спокійна, коли пояснює.','COLOR':'КОЛІР','CORE TOKENS':'БАЗОВІ ТОКЕНИ','pt grid':'сітка pt','px radius':'радіус px','px touch':'дотик px','ms motion':'анімація мс','Contrast':'Контраст','Text remains legible across soft surfaces.':'Текст залишається читабельним на м’яких поверхнях.','Non-color cues':'Сигнали поза кольором','State always includes shape, icon or label.':'Стан завжди має форму, іконку або підпис.','Motion restraint':'Стриманий рух','Clear labels':'Зрозумілі підписи','Security actions never rely on icons alone.':'Дії безпеки ніколи не покладаються лише на іконки.',
  'REFLECTION':'ВИСНОВКИ','What this concept proves—and what it does not.':'Що ця концепція доводить — і чого ні.','THE PRODUCT BET':'ПРОДУКТОВА ГІПОТЕЗА','Emotional comfort can be functional.':'Емоційний комфорт може бути функціональним.','Calm hierarchy, explicit confirmation and restrained motion do more than create a premium aesthetic. They can reduce hesitation and help users understand consequences before acting.':'Спокійна ієрархія, явне підтвердження та стриманий рух не лише створюють преміальну естетику. Вони зменшують вагання та допомагають зрозуміти наслідки до дії.','WHAT I’D VALIDATE NEXT':'ЩО Я ПЕРЕВІРИЛА Б ДАЛІ','Can users find card security controls without prompting?':'Чи знайдуть користувачі налаштування безпеки картки без підказки?','Do transfer review details reduce backtracking?':'Чи зменшують деталі перевірки переказу повернення назад?','Which home-screen modules earn their place?':'Які модулі головного екрана справді потрібні?','Does personalization increase attachment without distraction?':'Чи посилює персоналізація прихильність без відволікання?','01 · DISCOVER':'01 · ДОСЛІДЖЕННЯ','6 moderated interviews':'6 модерованих інтерв’ю','Map anxiety, routines and language around money movement.':'Дослідити тривоги, звички та мову навколо руху грошей.','02 · TEST':'02 · ТЕСТ','Task-based prototype':'Завданнєвий прототип','Transfer, freeze a card and understand monthly spend.':'Переказати гроші, заморозити картку та зрозуміти місячні витрати.','03 · MEASURE':'03 · ВИМІРЮВАННЯ','Confidence + completion':'Впевненість + завершення','Track success, errors, time, backtracking and perceived certainty.':'Виміряти успіх, помилки, час, повернення та відчуття впевненості.','Thank you for':'Дякую, що','following the thinking.':'простежили за процесом.','Back to visual project':'Назад до проєкту','Concept project':'Концептуальний проєкт'
};

Object.assign(pl,{
  'Good morning':'Dzień dobry','Total balance':'Łączne saldo','Recent activity':'Ostatnia aktywność','See all':'Zobacz wszystko','Today · Lifestyle':'Dzisiaj · Lifestyle','Yesterday · Groceries':'Wczoraj · Zakupy spożywcze','Send':'Wyślij','Pay':'Zapłać','Top up':'Doładuj','Review transfer':'Sprawdź przelew',"You're sending":'Wysyłasz','From':'Z konta','Fee':'Opłata','Arrival':'Dostarczenie','Today':'Dzisiaj','Confirm with Face ID':'Potwierdź przez Face ID','Encrypted and protected':'Zaszyfrowane i chronione','Month':'Miesiąc','Quarter':'Kwartał','Year':'Rok','Spent in May':'Wydano w maju','12% less than April':'12% mniej niż w kwietniu','Dining':'Restauracje','Travel':'Podróże','Transfer complete':'Przelew zakończony','View receipt':'Zobacz potwierdzenie','Done':'Gotowe'
});
Object.assign(uk,{
  'Good morning':'Доброго ранку','Total balance':'Загальний баланс','Recent activity':'Остання активність','See all':'Переглянути все','Today · Lifestyle':'Сьогодні · Lifestyle','Yesterday · Groceries':'Учора · Продукти','Send':'Надіслати','Pay':'Сплатити','Top up':'Поповнити','Review transfer':'Перевірка переказу',"You're sending":'Ви надсилаєте','From':'З рахунку','Fee':'Комісія','Arrival':'Надходження','Today':'Сьогодні','Confirm with Face ID':'Підтвердити через Face ID','Encrypted and protected':'Зашифровано та захищено','Month':'Місяць','Quarter':'Квартал','Year':'Рік','Spent in May':'Витрачено у травні','12% less than April':'На 12% менше, ніж у квітні','Dining':'Ресторани','Travel':'Подорожі','Transfer complete':'Переказ завершено','View receipt':'Переглянути квитанцію','Done':'Готово'
});

const dictionaries={pl,uk};
const normalize=value=>value
  .replaceAll('Â·','·').replaceAll('â€“','–').replaceAll('â€”','—')
  .replaceAll('â†’','→').replaceAll('â€ś','“').replaceAll('â€ť','”').replaceAll('â€™','’');
const reverse=new Map();
for(const dict of Object.values(dictionaries))for(const [key,value] of Object.entries(dict))reverse.set(value,key);

export function applyCaseLanguage(root,language){
  if(!root)return;
  root.setAttribute('lang',language==='uk'?'uk':language);
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
  for(const node of nodes){
    const raw=node.nodeValue;const trimmed=normalize(raw.trim());if(!trimmed)continue;
    const source=reverse.get(trimmed)||trimmed;
    const translated=language==='en'?source:(dictionaries[language]?.[source]||source);
    node.nodeValue=raw.replace(raw.trim(),translated);
  }
}
